version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    container_name: autocomplete-backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    container_name: autocomplete-frontend
    depends_on:
      - backend
